Sap::Category.create([
  ## -------------------------------------------------------------------------------------------
  {id: 100, name: 'Выпечка', url: 'bakery', order_pos: 100},
    {id: 101, name: 'Bread', url: 'bread', parent_id: 100},
    {id: 102, name: 'rolls-and-bagets', url: 'rolls-and-bagets', parent_id: 100},
    {id: 103, name: 'speciality-and-ethic-breads', url: 'speciality-and-ethic-breads', parent_id: 100},
    {id: 104, name: 'cakes', url: 'cakes', parent_id: 100},
    {id: 105, name: 'fresh-desserts', url: 'fresh-desserts', parent_id: 100},
    {id: 106, name: 'pies-and-tarts', url: 'pies-and-tarts', parent_id: 100},
    {id: 107, name: 'small-cakes-and-cookiees', url: 'small-cakes-and-cookiees', parent_id: 100},
    {id: 108, name: 'scones-teacakes-and-buns', url: 'scones-teacakes-and-buns', parent_id: 100},
    {id: 109, name: 'croissants-pastries', url: 'croissants-pastries', parent_id: 100},
    {id: 110, name: 'crumpets-pancakes-and-waffles', url: 'crumpets-pancakes-and-waffles', parent_id: 100},
  ## -------------------------------------------------------------------------------------------
  {id: 200, name: 'Овощи и Фрукты', url: 'fruit-and-vegetables', order_pos: 200},
    {id: 201, name: 'fruit', url: 'fruit', parent_id: 200},
    {id: 202, name: 'prepared-fruit', url: 'prepared-fruit', parent_id: 200},
    {id: 203, name: 'vegetables', url: 'vegetables', parent_id: 200},
    {id: 204, name: 'prepares-vegetables-and-salads', url: 'prepares-vegetables-and-salads', parent_id: 200},
    {id: 205, name: 'fresh-herbs', url: 'fresh-herbs', parent_id: 200},
    {id: 206, name: 'dried-fruit', url: 'dried-fruit', parent_id: 200},
    {id: 207, name: 'dried-vegetables', url: 'dried-vegetables', parent_id: 200},
  ## -------------------------------------------------------------------------------------------
  {id: 300, name: 'Молочные и Яйца', url: 'milk-and-eggs', order_pos: 300},
    {id: 301, name: 'fresh-milk', url: 'fresh-milk', parent_id: 300},
    {id: 302, name: 'shelf-milk', url: 'shelf-milk', parent_id: 300},
    {id: 303, name: 'cream', url: 'cream', parent_id: 300},
    {id: 304, name: 'eggs', url: 'eggs', parent_id: 300},
    {id: 305, name: 'butter-and-spreads', url: 'butter-and-spreads', parent_id: 300},
    {id: 306, name: 'cheese', url: 'cheese', parent_id: 300},
    {id: 307, name: 'yogurt', url: 'yogurt', parent_id: 300},
    {id: 308, name: 'yogurt-and-milk-drinks', url: 'yogurt-and-milk-drinks', parent_id: 300},
    {id: 309, name: 'chilled-desseerts', url: 'chilled-desseerts', parent_id: 300},
  ## -------------------------------------------------------------------------------------------
  {id: 400, name: 'Мясо Рыба Птица', url: 'meat-fish-poultry', order_pos: 400},
    {id: 401, name: 'fresh-meat', url: 'fresh-meat', parent_id: 400},
    {id: 402, name: 'fresh-poultry', url: 'fresh-poultry', parent_id: 400},
    {id: 403, name: 'cooked-prepared-meat-and-poultry', url: 'cooked-prepared-meat-and-poultry', parent_id: 400},
    {id: 404, name: 'fresh-and-prepared-fish', url: 'fresh-and-prepared-fish', parent_id: 400},
    {id: 405, name: 'smoked-and-marinated-fish', url: 'smoked-and-marinated-fish', parent_id: 400},
    {id: 406, name: 'pate', url: 'pate', parent_id: 400},
    {id: 407, name: 'bacon', url: 'bacon', parent_id: 400},
    {id: 408, name: 'sausages-and-burgers', url: 'sausages-and-burgers', parent_id: 400},
    {id: 409, name: 'deli-meat', url: 'deli-meat', parent_id: 400},
  ## -------------------------------------------------------------------------------------------
  {id: 500, name: 'Морозилка', url: 'frozen', order_pos: 500},
    {id: 501, name: 'ice-cream', url: 'ice-cream', parent_id: 500},
    {id: 502, name: 'frozen-desserts-and-fruit', url: 'frozen-desserts-and-fruit', parent_id: 500},
    {id: 503, name: 'frozen-meat', url: 'frozen-meat', parent_id: 500},
    {id: 504, name: 'frozen-poultry', url: 'frozen-poultry', parent_id: 500},
    {id: 505, name: 'frozen-fish-and-seafood', url: 'frozen-fish-and-seafood', parent_id: 500},
    {id: 506, name: 'frozen-chips-and-potatoes', url: 'frozen-chips-and-potatoes', parent_id: 500},
    {id: 507, name: 'frozen-vegetables', url: 'frozen-vegetables', parent_id: 500},
    {id: 508, name: 'frozen-pizza-and-breads', url: 'frozen-pizza-and-breads', parent_id: 500},
    {id: 509, name: 'frozen-ready-meals', url: 'frozen-ready-meals', parent_id: 500},
    {id: 510, name: 'frozen-vegetarian', url: 'frozen-vegetarian', parent_id: 500},
  ## -------------------------------------------------------------------------------------------
  {id: 600, name: 'Кулинария', url: 'ready-meals', order_pos: 600},
    {id: 601, name: 'fresh-pasta', url: 'fresh-pasta', parent_id: 600},
    {id: 602, name: 'fresh-world-foods', url: 'fresh-world-foods', parent_id: 600},
    {id: 603, name: 'fresh-meal', url: 'fresh-meal', parent_id: 600},
    {id: 604, name: 'fresh-marinades-ans-sauces', url: 'fresh-marinades-ans-sauces', parent_id: 600},
    {id: 605, name: 'fresh-pizza-and-chilled-bread', url: 'fresh-pizza-and-chilled-bread', parent_id: 600},
    {id: 606, name: 'fresh-vegetarian-food', url: 'fresh-vegetarian-food', parent_id: 600},
    {id: 607, name: 'fresh-soup', url: 'fresh-soup', parent_id: 600},
    {id: 608, name: 'dips-and-fillers', url: 'dips-and-fillers', parent_id: 600},
    {id: 609, name: 'pies-and-quiches', url: 'pies-and-quiches', parent_id: 600},
    {id: 610, name: 'savoury-rolls-and-snacks', url: 'savoury-rolls-and-snacks', parent_id: 600},
    {id: 611, name: 'sandwiches-and-wraps', url: 'sandwiches-and-wraps', parent_id: 600},
  ## -------------------------------------------------------------------------------------------
  {id: 700, name: 'Консервы и Приправы', url: 'tin-jars-cooking', order_pos: 700},
    {id: 701, name: 'oils-and-vinegar', url: 'oils-and-vinegar', parent_id: 700},
    {id: 702, name: 'salt-and-pepper', url: 'salt-and-pepper', parent_id: 700},
    {id: 703, name: 'herbs-and-spices', url: 'herbs-and-sspices', parent_id: 700},
    {id: 704, name: 'tinned-beans', url: 'tinned-beans', parent_id: 700},
    {id: 705, name: 'tinned-tomatoes-puree-and-passata', url: 'tinned-tomatoes-puree-and-passata', parent_id: 700},
    {id: 706, name: 'tinned-vegetables', url: 'tinned-vegetables', parent_id: 700},
    {id: 707, name: 'tinned-fish', url: 'tinned-fish', parent_id: 700},
    {id: 708, name: 'tinned-soup', url: 'tinned-soup', parent_id: 700},
    {id: 709, name: 'tinned-pasta', url: 'tinned-pasta', parent_id: 700},
    {id: 710, name: 'tinned-meal-and-poultry', url: 'tinned-meal-and-poultry', parent_id: 700},
    {id: 711, name: 'tinned-fruit', url: 'tinned-fruit', parent_id: 700},
    {id: 712, name: 'pickles-and-marinated-vegetables', url: 'pickles-and-marinated-vegetables', parent_id: 700},
    {id: 713, name: 'mayonnaise-and-dressings', url: 'mayonnaise-and-dressings', parent_id: 700},
    {id: 714, name: 'marinades-and-sauces', url: 'marinades-and-sauces', parent_id: 700},
    {id: 715, name: 'pasta-sauce', url: 'pasta-sauce', parent_id: 700},
    {id: 716, name: 'condiments', url: 'condiments', parent_id: 700},
    {id: 717, name: 'jam-and-spreads', url: 'jam-and-spreads', parent_id: 700},
    {id: 718, name: 'curry-sauce-and-paste', url: 'curry-sauce-and-paste', parent_id: 700},
    {id: 719, name: 'stock-sauce-mix-and-gravy', url: 'stock-sauce-mix-and-gravy', parent_id: 700},
  ## -------------------------------------------------------------------------------------------
  {id: 800, name: 'Бакалея', url: 'packets-and-cereals', order_pos: 800},
    {id: 801, name: 'breakfast-cereals', url: 'breakfast-cereals', parent_id: 800},
    {id: 802, name: 'porridge-and-muesli', url: 'porridge-and-muesli', parent_id: 800},
    {id: 803, name: 'cereal-bars', url: 'cereal-bars', parent_id: 800},
    {id: 804, name: 'home-baking', url: 'home-baking', parent_id: 800},
    {id: 805, name: 'flour', url: 'flour', parent_id: 800},
    {id: 806, name: 'sugar-and-sweetener', url: 'sugar-and-sweetener', parent_id: 800},
    {id: 807, name: 'pasta-end-noodles', url: 'pasta-end-noodles', parent_id: 800},
    {id: 808, name: 'rice-pulses-and-grain', url: 'rice-pulses-and-grain', parent_id: 800},
    {id: 809, name: 'packet-soup', url: 'packet-soup', parent_id: 800},
    {id: 810, name: 'stuffing-and-breadcrumbs', url: 'stuffing-and-breadcrumbs', parent_id: 800},
    {id: 811, name: 'desserts', url: 'desserts', parent_id: 800},
  ## -------------------------------------------------------------------------------------------
  {id: 900, name: 'Кондитерские', url: 'snacks-and-sweets', order_pos: 900},
    {id: 901, name: 'chocolate-biscuits', url: 'chocolate-biscuits', parent_id: 900},
    {id: 902, name: 'biscuites', url: 'biscuites', parent_id: 900},
    {id: 903, name: 'crisps', url: 'crisps', parent_id: 900},
    {id: 904, name: 'snacks', url: 'snacks', parent_id: 900},
    {id: 905, name: 'nuts-and-seeds', url: 'nuts-and-seeds', parent_id: 900},
    {id: 906, name: 'crackers-and-crispbreads', url: 'crackers-and-crispbreads', parent_id: 900},
    {id: 907, name: 'mints-and-gum', url: 'mints-and-gum', parent_id: 900},
    {id: 908, name: 'sweets', url: 'sweets', parent_id: 900},
    {id: 909, name: 'chocolate-bars-bags-and-multipacks', url: 'chocolate-bars-bags-and-multipacks', parent_id: 900},
    {id: 910, name: 'boxed-chocolate', url: 'boxed-chocolate', parent_id: 900},
  ## -------------------------------------------------------------------------------------------
  {id: 1000, name: 'Напитки', url: 'drinks', order_pos: 1000},
    {id: 1001, name: 'ground-coffee', url: 'ground-coffee', parent_id: 1000},
    {id: 1002, name: 'instant-coffee', url: 'instant-coffee', parent_id: 1000},
    {id: 1003, name: 'tea', url: 'tea', parent_id: 1000},
    {id: 1004, name: 'chocolate-and-malt-drinks', url: 'chocolate-and-malt-drinks', parent_id: 1000},
    {id: 1005, name: 'mineral-water', url: 'mineral-water', parent_id: 1000},
    {id: 1006, name: 'sports-and-energy-drinks', url: 'sports-and-energy-drinks', parent_id: 1000},
    {id: 1007, name: 'fizzy-drinks', url: 'fizzy-drinks', parent_id: 1000},
    {id: 1008, name: 'squash-and-cordials', url: 'squash-and-cordials', parent_id: 1000},
    {id: 1009, name: 'longlife-juice-drinks', url: 'longlife-juice-drinks', parent_id: 1000},
    {id: 1010, name: 'longlife-juice-drinks', url: 'longlife-juice-drinks', parent_id: 1000},
    {id: 1011, name: 'chilled-fruit-juice-and-smoothies', url: 'chilled-fruit-juice-and-smoothies', parent_id: 1000},
    {id: 1012, name: 'adult-drinks-and-mixers', url: 'adult-drinks-and-mixers', parent_id: 1000},
    {id: 1013, name: 'beer', url: 'beer', parent_id: 1000},
    {id: 1014, name: 'cider', url: 'cider', parent_id: 1000},
    {id: 1015, name: 'white-wine', url: 'white-wine', parent_id: 1000},
    {id: 1016, name: 'red-wine', url: 'red-wine', parent_id: 1000},
    {id: 1017, name: 'rose-and-specialty-wine', url: 'rose-and-specialty-wine', parent_id: 1000},
    {id: 1018, name: 'champagne-and-sparkling-wines', url: 'champagne-and-sparkling-wines', parent_id: 1000},
    {id: 1019, name: 'spirits', url: 'spirits', parent_id: 1000},
    {id: 1020, name: 'sherry-port-and-vermouth', url: 'sherry-port-and-vermouth', parent_id: 1000},
    {id: 1021, name: 'gifts-and-cases', url: 'gifts-and-cases', parent_id: 1000},
  ## -------------------------------------------------------------------------------------------
  {id: 1100, name: 'Для дома', url: 'household', order_pos: 1100},
    {id: 1101, name: 'household-cleaning', url: 'household-cleaning', parent_id: 1100},
    {id: 1102, name: 'cleaning-accessories', url: 'cleaning-accessories', parent_id: 1100},
    {id: 1103, name: 'dishwashing', url: 'dishwashing', parent_id: 1100},
    {id: 1104, name: 'laundry', url: 'laundry', parent_id: 1100},
    {id: 1105, name: 'air-freshener', url: 'air-freshener', parent_id: 1100},
    {id: 1106, name: 'scented-oils-candles-pot-pourri', url: 'scented-oils.candles.pot-pourri', parent_id: 1100},
    {id: 1107, name: 'party-accessories', url: 'party-accessories', parent_id: 1100},
    {id: 1108, name: 'tissues-and-toilets-rols', url: 'tissues-and-toilets-rols', parent_id: 1100},
    {id: 1109, name: 'light-bulbs', url: 'light-bulbs', parent_id: 1100},
    {id: 1110, name: 'candles.firelighters-and-matches', url: 'candles-firelighters-and-matches', parent_id: 1100},
    {id: 1111, name: 'tobacconist', url: 'tobacconist', parent_id: 1100},
    {id: 1112, name: 'batteries-films-and-blank-media', url: 'batteries-films-and-blank-media', parent_id: 1100},
    {id: 1113, name: 'newsagent', url: 'newsagent', parent_id: 1100},
    {id: 1114, name: 'stationery', url: 'stationery', parent_id: 1100},
    {id: 1115, name: 'disposable-tableware', url: 'disposable-tableware', parent_id: 1100},
  ## -------------------------------------------------------------------------------------------
  {id: 1200, name: 'Для животных', url: 'pets', order_pos: 1200},
    {id: 1201, name: 'dog-food', url: 'dog-food', parent_id: 1200},
    {id: 1202, name: 'cat-food', url: 'cat-food', parent_id: 1200},
    {id: 1203, name: 'pet-care', url: 'pet-care', parent_id: 1200},
    {id: 1204, name: 'other-pet-food', url: 'other-pet-food', parent_id: 1200},
  ## -------------------------------------------------------------------------------------------
  {id: 1300, name: 'Детям', url: 'baby', order_pos: 1300},
    {id: 1301, name: 'nappies', url: 'nappies', parent_id: 1300},
    {id: 1302, name: 'nappy-accessories', url: 'nappy-accessories', parent_id: 1300},
    {id: 1303, name: 'baby-care', url: 'baby-care', parent_id: 1300},
    {id: 1304, name: 'baby-feeding', url: 'baby-feeding', parent_id: 1300},
    {id: 1305, name: 'baby-milk-and-drinks', url: 'baby-milk-and-drinks', parent_id: 1300},
    {id: 1306, name: 'baby-food-and-snacks', url: 'baby-food-and-snacks', parent_id: 1300},
  ## -------------------------------------------------------------------------------------------
  {id: 1400, name: 'Гигиена', url: 'health-and-beauty', order_pos: 1400},
    {id: 1401, name: 'bath-shower-soap', url: 'bath-shower-soap', parent_id: 1400},
    {id: 1402, name: 'shampoo-and-conditioner', url: 'shampoo-and-conditioner', parent_id: 1400},
    {id: 1403, name: 'hair-care', url: 'hair-care', parent_id: 1400},
    {id: 1404, name: 'fragrance', url: 'fragrance', parent_id: 1400},
    {id: 1405, name: 'deodorants-and-body-spray', url: 'deodorants-and-body-spray', parent_id: 1400},
    {id: 1406, name: 'body-care', url: 'body-care', parent_id: 1400},
    {id: 1407, name: 'make-up', url: 'make-up', parent_id: 1400},
    {id: 1408, name: 'eye-make-up', url: 'eye-make-up', parent_id: 1400},
    {id: 1409, name: 'lip-products', url: 'lip-products', parent_id: 1400},
    {id: 1410, name: 'nail-care', url: 'nail-care', parent_id: 1400},
    {id: 1411, name: 'facial-care', url: 'facial-care', parent_id: 1400},
    {id: 1412, name: 'hair-removal', url: 'hair-removal', parent_id: 1400},
    {id: 1413, name: 'mens-toiletries', url: 'mens-toiletries', parent_id: 1400},
    {id: 1414, name: 'dental', url: 'dental', parent_id: 1400},
    {id: 1415, name: 'feminine', url: 'feminine', parent_id: 1400},
    {id: 1416, name: 'womens-health', url: 'womens-health', parent_id: 1400},
    {id: 1417, name: 'sexual-health', url: 'sexual-health', parent_id: 1400},
    {id: 1418, name: 'suncare-and-bronzing', url: 'suncare-and-bronzing', parent_id: 1400},
    {id: 1419, name: 'weight-loss', url: 'weight-loss', parent_id: 1400},
    {id: 1420, name: 'first-aid', url: 'first-aid', parent_id: 1400},
    {id: 1421, name: 'general-health', url: 'general-health', parent_id: 1400},
    {id: 1422, name: 'vitamins-and-supplemets', url: 'vitamins-and-supplemets', parent_id: 1400},
    {id: 1423, name: 'medicine', url: 'medicine', parent_id: 1400},
    {id: 1424, name: 'beauty-gifts-sets', url: 'beauty-gifts-sets', parent_id: 1400},
])